'use strict';
// Shared browser settings; never put real API keys in this file.
window.VertexHub=(()=>{
 const ROOT=new URL('.',document.currentScript.src||location.href),SCOPE='vertex-hub:'+ROOT.pathname,SETTINGS=SCOPE+':ai',ACCESS=SCOPE+':access';
 const HASH='0e7ba1c1a960f6da5a9567b6c25f49c61dff0ad7be4a8c1008f097926c47ec06';
 function load(){try{const d=JSON.parse(localStorage.getItem(SETTINGS)||'null');if(d)return d;}catch{}return{key1:'',key2:'',active:'key1',model:'gemini-3.5-flash'};}
 function save(d){const clean={key1:String(d.key1||'').trim(),key2:String(d.key2||'').trim(),active:'key1',model:String(d.model||'gemini-3.5-flash')};if(!clean[clean.active])throw Error('Enter a key for the selected API slot.');if(!/^[a-zA-Z0-9._-]+$/.test(clean.model))throw Error('Check the model ID.');localStorage.setItem(SETTINGS,JSON.stringify(clean));return clean;}
 function clear(){localStorage.removeItem(SETTINGS);}
 function unlocked(){try{return sessionStorage.getItem(ACCESS)===HASH;}catch{return false;}}
 async function unlock(password){if(!crypto.subtle)throw Error('Open this website through HTTPS or localhost.');const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(password));const digest=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');if(digest!==HASH)return false;sessionStorage.setItem(ACCESS,HASH);return true;}
 function lock(){sessionStorage.removeItem(ACCESS);location.replace(new URL('index.html',ROOT));}
 function requireAccess(){if(unlocked())return true;document.documentElement.setAttribute('data-vertex-locked','');if(!document.getElementById('vertex-gate-style')){const style=document.createElement('style');style.id='vertex-gate-style';style.textContent='html[data-vertex-locked] body > :not(#vertex-entry){display:none!important}#vertex-entry{position:fixed;inset:0;z-index:999999;background:#f3f6f9;display:grid;place-items:center;font:16px/1.5 system-ui,sans-serif;color:#163047;padding:20px}#vertex-entry form{background:white;padding:28px;border:1px solid #dce5ec;border-radius:14px;width:100%;max-width:380px}#vertex-entry h1{font-size:26px;margin:0 0 8px}#vertex-entry p{font-size:14px;color:#617385}#vertex-entry label{display:block;margin-bottom:6px}#vertex-entry input{box-sizing:border-box;width:100%;padding:12px;border:1px solid #bccbd5;border-radius:8px;font:inherit}#vertex-entry button{width:100%;padding:12px;background:#086c59;color:white;border:0;border-radius:8px;margin-top:16px;font:inherit;font-weight:650}#vertex-entry .error{color:#b23849;min-height:20px}';document.head.append(style);}const mount=()=>{if(document.getElementById('vertex-entry'))return;const entry=document.createElement('section');entry.id='vertex-entry';entry.innerHTML='<form><h1>Test 1</h1><p>Enter your password to open practice.</p><label for="vertex-password">Password</label><input id="vertex-password" type="password" autocomplete="current-password" required><button>Open Test 1</button><p class="error" role="status"></p></form>';document.body.append(entry);entry.querySelector('form').onsubmit=async event=>{event.preventDefault();try{if(!await unlock(entry.querySelector('input').value)){entry.querySelector('.error').textContent='Incorrect password. Try again.';return;}document.documentElement.removeAttribute('data-vertex-locked');entry.remove();}catch(e){entry.querySelector('.error').textContent=e.message;}};entry.querySelector('input').focus();};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();return false;}

 return{load,save,clear,unlocked,unlock,lock,requireAccess,settingsKey:SETTINGS,root:ROOT};
})();
