'use strict';
const el=id=>document.getElementById(id),hub=VertexHub;
function refreshStatus(){const s=hub.load();el('aiStatus').textContent=s.provider==='lmstudio'?'LM Studio · '+(s.localModel||'Setup needed'):s.key1?'AI ready'+(s.key2?' · Backup saved':''):'AI not configured';}
function showHome(){el('login').classList.add('hidden');el('home').classList.remove('hidden');el('headerActions').classList.remove('hidden');el('password').value='';el('testList').replaceChildren();for(const t of VERTEX_TESTS){const row=document.createElement('article');row.className='test-row';const text=document.createElement('div'),title=document.createElement('h2'),note=document.createElement('p');title.textContent=t.name;note.textContent=t.description;note.className='muted';text.append(title,note);row.append(text);if(t.ready){const a=document.createElement('a');a.href=t.file;a.className='button primary';a.textContent='Open';row.append(a);}else{const label=document.createElement('span');label.className='badge';label.textContent='Coming next';row.append(label);}el('testList').append(row);}refreshStatus();if(location.hash==='#ai')openAI();}
function openAI(){const s=hub.load();el('billing1').value=s.billing1||'free';el('billing2').value=s.billing2||'paid';el('inputRate').value=s.inputRate??'';el('outputRate').value=s.outputRate??'';el('key1').value=s.key1||'';el('key2').value=s.key2||'';el('model').value=s.model||'gemini-3.5-flash';el('provider').value=s.provider||'gemini';el('localUrl').value=s.localUrl||'http://localhost:1234/v1';el('localToken').value=s.localToken||'';el('localModel').replaceChildren(new Option(s.localModel||'Connect to select a model',s.localModel||''));toggleProvider();el('aiError').textContent='';el('aiDialog').showModal();}
el('loginForm').onsubmit=async e=>{e.preventDefault();try{if(!await hub.unlock(el('password').value)){el('loginError').textContent='Incorrect password. Try again.';return;}const next=new URLSearchParams(location.search).get('next');if(VERTEX_TESTS.some(t=>t.ready&&t.file===next)){location.replace(next);return;}showHome();}catch(error){el('loginError').textContent=error.message;}};
el('aiSetup').onclick=openAI;el('closeAI').onclick=()=>el('aiDialog').close();el('lockSite').onclick=hub.lock;
el('aiForm').onsubmit=e=>{e.preventDefault();try{hub.save({billing1:el('billing1').value,billing2:el('billing2').value,inputRate:el('inputRate').value,outputRate:el('outputRate').value,provider:el('provider').value,localUrl:el('localUrl').value,localModel:el('localModel').value,localToken:el('localToken').value,key1:el('key1').value,key2:el('key2').value,active:'key1',model:el('model').value.trim()});refreshStatus();el('aiDialog').close();}catch(error){el('aiError').textContent=error.message;}};
el('clearKeys').onclick=()=>{try{hub.clear();el('key1').value='';el('key2').value='';el('localToken').value='';refreshStatus();el('aiError').textContent='Saved AI settings and tokens removed.';}catch{el('aiError').textContent='Browser could not remove the keys. Clear site data in browser settings.';}};
window.addEventListener('pageshow',()=>{if(!hub.unlocked()){el('home').classList.add('hidden');el('headerActions').classList.add('hidden');el('login').classList.remove('hidden');}});
if(hub.unlocked())showHome();

function toggleProvider(){el('geminiFields').classList.toggle('hidden',el('provider').value==='lmstudio');el('localFields').classList.toggle('hidden',el('provider').value!=='lmstudio');}
el('provider').onchange=toggleProvider;
function localSettings(){return {localUrl:el('localUrl').value,localModel:el('localModel').value,localToken:el('localToken').value};}
el('connectLocal').onclick=async()=>{const button=el('connectLocal');button.disabled=true;el('aiError').textContent='Connecting…';try{const data=await hub.localRequest(localSettings(),'/models');const ids=(data.data||[]).filter(x=>typeof x.id==='string'&&!/embed/i.test(x.id)).map(x=>x.id);if(!ids.length)throw Error('No text models found. Download and load a model in LM Studio.');const previous=el('localModel').value;el('localModel').replaceChildren(...ids.map(id=>new Option(id,id)));if(ids.includes(previous))el('localModel').value=previous;el('aiError').textContent='Connected. Select a model and test it.';}catch(e){el('aiError').textContent=e.message;}finally{button.disabled=false;}};
el('testLocal').onclick=async()=>{const button=el('testLocal');button.disabled=true;el('aiError').textContent='Testing structured output…';try{if(!el('localModel').value)throw Error('Connect and choose a model first.');const data=await hub.localGenerate(localSettings(),'Return JSON with answer equal to 2 + 3.',{type:'object',properties:{answer:{type:'integer'}},required:['answer'],additionalProperties:false});if(data.answer!==5)throw Error('Model test returned an incorrect answer. Try another model.');el('aiError').textContent='Model test passed. Save to use LM Studio.';}catch(e){el('aiError').textContent=e.message;}finally{button.disabled=false;}};
