'use strict';
const el=id=>document.getElementById(id),hub=VertexHub;
function refreshStatus(){const s=hub.load();el('aiStatus').textContent=s.key1?'AI ready'+(s.key2?' · Backup saved':''):'AI not configured';}
function showHome(){el('login').classList.add('hidden');el('home').classList.remove('hidden');el('headerActions').classList.remove('hidden');el('password').value='';el('testList').replaceChildren();for(const t of VERTEX_TESTS){const row=document.createElement('article');row.className='test-row';const text=document.createElement('div'),title=document.createElement('h2'),note=document.createElement('p');title.textContent=t.name;note.textContent=t.description;note.className='muted';text.append(title,note);row.append(text);if(t.ready){const a=document.createElement('a');a.href=t.file;a.className='button primary';a.textContent='Open';row.append(a);}else{const label=document.createElement('span');label.className='badge';label.textContent='Coming next';row.append(label);}el('testList').append(row);}refreshStatus();if(location.hash==='#ai')openAI();}
function openAI(){const s=hub.load();el('key1').value=s.key1||'';el('key2').value=s.key2||'';el('model').value=s.model||'gemini-3.5-flash';el('aiError').textContent='';el('aiDialog').showModal();}
el('loginForm').onsubmit=async e=>{e.preventDefault();try{if(!await hub.unlock(el('password').value)){el('loginError').textContent='Incorrect password. Try again.';return;}const next=new URLSearchParams(location.search).get('next');if(VERTEX_TESTS.some(t=>t.ready&&t.file===next)){location.replace(next);return;}showHome();}catch(error){el('loginError').textContent=error.message;}};
el('aiSetup').onclick=openAI;el('closeAI').onclick=()=>el('aiDialog').close();el('lockSite').onclick=hub.lock;
el('aiForm').onsubmit=e=>{e.preventDefault();try{hub.save({key1:el('key1').value,key2:el('key2').value,active:'key1',model:el('model').value.trim()});refreshStatus();el('aiDialog').close();}catch(error){el('aiError').textContent=error.message;}};
el('clearKeys').onclick=()=>{try{hub.clear();el('key1').value='';el('key2').value='';refreshStatus();el('aiError').textContent='Both saved keys removed.';}catch{el('aiError').textContent='Browser could not remove the keys. Clear site data in browser settings.';}};
window.addEventListener('pageshow',()=>{if(!hub.unlocked()){el('home').classList.add('hidden');el('headerActions').classList.add('hidden');el('login').classList.remove('hidden');}});
if(hub.unlocked())showHome();
